// <auto-generated />
using InteractiveLeads.Infrastructure.Context.Application;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace InteractiveLeads.Infrastructure.Migrations.Application
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260330195000_AddWhatsAppTemplateSubmissionError")]
    partial class AddWhatsAppTemplateSubmissionError
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            // Intentionally empty: current model is tracked in ApplicationDbContextModelSnapshot only.
            // The Up/Down migration defines the schema delta for this migration id.
#pragma warning restore 612, 618
        }
    }
}
